#!/usr/bin/env bash
# redirecting

# update server
sudo apt-get update

#install nginx
sudo apt-get -y install nginx

# on GET request
cat <<EOF | sudo tee /etc/nginx/sites-available/redirect_me
server {
        listen 80;
        listen [::]:80;

        server_name _;

        location / {
       		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 }
}
EOF
#start server
sudo service nginx restart

