#!/usr/bin/env bash
# redirecting

# update server
sudo apt-get update

#install nginx
sudo apt-get -y install nginx

# on GET request
echo 'Hello World!' | sudo tee /var/www/html/index.html

#configure server
sudo printf "server {
    listen 80;
    listen [::]:80;
    server_name _;
    }ocation /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}" | tee /etc/nginx/sites-available/redirect_me

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/redirect_me

#affirm config
sudo nginx -t

#start server
sudo service nginx reload
