#!/usr/bin/env bash
# 404 not found

# update server
sudo apt-get update

#install nginx
sudo apt-get -y install nginx

# on GET request
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

#configure server
sudo printf "server {
    listen 80;
    listen [::]:80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
	}
}" | tee /etc/nginx/sites-available/default

#start server
sudo service nginx restart 
