#!/usr/bin/env bash
# 404 not found

# update server
sudo apt-get update

#install nginx
sudo apt-get -y install nginx

# on GET request
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

hostname=$(hostname)

#configure server
sudo printf "server {
	listen 8;
        listen [::]:80 default_server;
        add_header X-Served-By $hostname;
        root /var/www/html;
        index index.html index.html index.htm index.nginx-debian.html;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html/;
                internal;
        }
}" > /etc/nginx/sites-available/default

# restart server
sudo service nginx restart
