#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

# update
sudo apt-get update

#install nginx
sudi apt-get install -y nginx

# on GET request
echo 'Hello World!' | sudo tee /var/www/html/index.html


# configure server
sudo printf 'server' {
	
	
