#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

# update
sudo apt-get update

#install nginx
sudo apt-get install -y nginx

# on GET request
echo 'Hello World!' | sudo tee /var/www/html/index.html

# on Error
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Get the hostname of the machine
hostname=$(hostname)

# configure server
sudo printf "server {
	listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $hostname;
    root /var/www/html;
    index index.html index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.github.com/Cofucan;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html/;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx server
sudo service nginx restart
