#!/usr/bin/env bash
# A bash script for nginx server to listen at port 80

# remove the default file 
sudo rm /etc/nginx/sites-enable/default

# create a symbolic link
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enable/default
# Restart Nginx
sudo service nginx restart
