#!/usr/bin/env bash
# Script that display I am invincible!!! when receiving a SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM

infinite=1
while [ $infinite ]; do
	echo "To infinity and beyond"
	sleep 2
done
	
