#!/usr/bin/env bash
# This script is displaying number 1 to 20
# 4th, 9th, and 17th iteration define
num=1
while [ $num -le 20 ]; do
        if [ $num -eq 4 ]; then
		echo "$num"
                echo 'bad luck from China'
        elif [ $num -eq 9 ]; then
		echo "$num"
                echo 'bad luck from Japan'
	elif [ $num -eq 17 ]; then
		echo "$num"
		echo 'bad luck from Italy'
        else
                echo "$num"
        fi
	((num++))
done 
