#!/usr/bin/env bash
# This script is displaying number 1 to 20
# 4th, 9th, and 17th iteration define
for i in {1..20}; do
        if [ $i -eq 4 ]; then
		echo "$i"
                echo 'bad luck from China'
        elif [ $i -eq 9 ]; then
		echo "$i"
                echo 'bad luck from Japan'
	elif [ $i -eq 17 ]; then
		echo "$i"
		echo 'bad luck from Italy'
        else
                echo "$i"
        fi
done 
