#!/usr/bin/env bash
# This script is displaying number 1 to 20
# after 4 it display bad luck from China
# after 9 it display bad luck from Japan
#after 17 it display bad luck from Italy
for i in {1..20}; do
        if [ $i -eq 4 ]; then
		echo "$i"
                echo 'bad luck from China'
        elif [ $i -eq 9 ]; then
		echo "$i"
                echo 'bad luck from Japan'
	elif [ $i -eq 17 ]; then
		echo "$i"
		echo 'bad luck from Italy'
        else
                echo "$i"
        fi
done 
